leftnav:
- identifier: 0c8a4c3f-3e73-1cb5-9766-9ad41776bd63
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e7344c0d-d06d-e205-c09f-d7d0b2cc6958
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9158a8f0-c053-4144-f55f-efacd305f3f5
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 75d54fc3-032c-35b4-49de-966608dbca41
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: fbde3dc2-de9f-7f1f-98d2-6548acb89d56
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
